export  const pakages = [
    {
        id:'1'
        ,name:'wheet'
        ,weight:'20'
    },
    {
        id:'2'
        ,name:'rice'
        ,weight:'30'
    },
    {
        id:'3'
        ,name:'friege'
        ,weight:'30'
    },
    {
        id:'4'
        ,name:'book'
        ,weight:'40'
    },
    {
        id:'5'
        ,name:'book'
        ,weight:'15'
    },
    {
        id:'6'
        ,name:'book'
        ,weight:'2'
    },
    {
        id:'7'
        ,name:'book'
        ,weight:'8'
    },
    {
        id:'8'
        ,name:'book'
        ,weight:'90'
    },
    {
        id:'9'
        ,name:'book'
        ,weight:'69'
    },
    {
        id:'10'
        ,name:'book'
        ,weight:'250'
    },
    {
        id:'11'
        ,name:'book'
        ,weight:'100'
    },
    {
        id:'12'
        ,name:'book'
        ,weight:'165'
    },
    {
        id:'13'
        ,name:'book'
        ,weight:'250'
    },
    {
        id:'14'
        ,name:'book'
        ,weight:'300'
    },
]