export const parcels = [
{id: 1, name: 'Box', weight: 10 },
{id: 2, name: 'Crate', weight: 20 },
{id: 3, name: 'Barrel', weight: 30 },
{id: 4, name: 'Bag', weight: 5 },
{id: 5, name: 'Pallet', weight: 100 },
{id: 6, name: 'Drum', weight: 50 },
{id: 7, name: 'Canister', weight: 15 },
{id: 8, name: 'Bar', weight: 40 },
{id: 9, name: 'Tube', weight: 3 },
{id: 10, name: 'Sphere', weight: 25 },
{id: 11, name: 'Envelope', weight: 0.5 },
{id: 12, name: 'Bag', weight: 7 },
{id: 13, name: 'Crate', weight: 15 },
{id: 14, name: 'Cylinder', weight: 12 },
{id: 15, name: 'Box', weight: 8 },
{id: 16, name: 'Pallet', weight: 75 },
{id: 17, name: 'Bag', weight: 2 },
{id: 18, name: 'Drum', weight: 45 },
{id: 19, name: 'Canister', weight: 18 },
{id: 20, name: 'Bar', weight: 35 },
{id: 21, name: 'Sphere', weight: 20 },
{id: 22, name: 'Box', weight: 9 },
{id: 23, name: 'Crate', weight: 25 },
{id: 24, name: 'Barrel', weight: 35 },
{id: 25, name: 'Bag', weight: 6 },
{id: 26, name: 'Pallet', weight: 90 },
{id: 27, name: 'Drum', weight: 55 },
{id: 28, name: 'Canister', weight: 10 },
{id: 29, name: 'Bar', weight: 50 },
{id: 30, name: 'Tube', weight: 2 },
{id: 31, name: 'Sphere', weight: 30 },
{id: 32, name: 'Envelope', weight: 0.3 },
{id: 33, name: 'Box', weight: 12 },
{id: 34, name: 'Crate', weight: 18 },
{id: 35, name: 'Cylinder', weight: 15 },
{id: 36, name: 'Bag', weight: 4 },
{id: 37, name: 'Pallet', weight: 80 },
{id: 38, name: 'Drum', weight: 60 },
{id: 39, name: 'Canister', weight: 20 },
{id: 40, name: 'Bar', weight: 45 },
{id: 41, name: 'Sphere', weight: 18 },
{id: 42, name: 'Box', weight: 6 },
{id: 43, name: 'Book', weight: 2},
{id: 44, name: 'Pen', weight: 0.5},
{id: 45, name: 'Laptop', weight: 3},
{id: 46, name: 'Mouse', weight: 0.2},
{id: 47, name: 'Keyboard', weight: 1},
{id: 48, name: 'Phone Charger', weight: 0.1},
{id: 49, name: 'Headphones', weight: 0.5},
{id: 50, name: 'Sunglasses', weight: 0.2},
{id: 51, name: 'Water Bottle', weight: 0.5},
{id: 52, name: 'Wallet', weight: 0.2},
{id: 53, name: 'Umbrella', weight: 0.8},
{id: 54, name: 'T-Shirt', weight: 0.3},
{id: 55, name: 'Shorts', weight: 0.4},
{id: 56, name: 'Sneakers', weight: 0.7},
{id: 57, name: 'Hat', weight: 0.2},
{id: 58, name: 'Socks', weight: 0.1},
{id: 59, name: 'Toothbrush', weight: 0.1},
{id: 60, name: 'Toothpaste', weight: 0.2},
{id: 61, name: 'Shampoo', weight: 0.4},
{id: 62, name: 'Conditioner', weight: 0.4},
{id: 63, name: 'Soap', weight: 0.2},
{id: 64, name: 'Towel', weight: 0.6},
{id: 65, name: 'Glasses', weight: 0.3},
{id: 66, name: 'Medicine', weight: 0.2},
{id: 67, name: 'Lotion', weight: 0.3},
{id: 68, name: 'Deodorant', weight: 0.1},
{id: 69, name: 'Sunscreen', weight: 0.4},
{id: 70, name: 'Hand Sanitizer', weight: 0.2},
{id: 71, name: 'Mask', weight: 0.1},
{id: 72, name: 'Gloves', weight: 0.1},
{id: 73, name: 'Earplugs', weight: 0.1},
{id: 74, name: 'Pillow', weight: 0.8},
{id: 75, name: 'Blanket', weight: 0.7},
{id: 76, name: 'Lip Balm', weight: 0.1},
{id: 77, name: 'Snacks', weight: 0.6},
{id: 78, name: 'Gum', weight: 0.1},
{id: 79, name: 'Chapstick', weight: 0.1},
{id: 80, name: 'Snacks', weight: 10.2 },
{id: 81, name: 'Gum', weight: 5 },
{id: 82, name: 'Chapstick', weight: 11 },
{id: 83, name: 'Chapstick', weight: 11 },
{id: 84, name: 'Chapstick', weight: 11 },
{id: 85, name: 'KK', weight: 1 },
{id: 86, name: 'Snacks', weight: 1 },
{id: 87, name: 'Snacks', weight: 10 },
{id: 88, name: 'Snacks', weight: 2 },
{id: 90, name: 'Snacks', weight: 10.2 },
{id: 91, name: 'Lip Balm', weight: 0.1},
{id: 92, name: 'Snacks', weight: 0.6},
{id: 93, name: 'Gum', weight: 0.1},
{id: 94, name: 'Chapstick', weight: 0.1},
{id: 95, name: 'Snacks', weight: 10.2 },
{id: 96, name: 'Gum', weight: 5 },
{id: 97, name: 'Chapstick', weight: 11 },
{id: 98, name: 'KK', weight: 1 },
{id: 99, name: 'Snacks', weight: 1 },
{id: 100, name: 'Snacks', weight: 2 },
{id: 101, name: 'Snacks', weight: 10.2 },
]

export const truckDetails = [
    {
        type: "cargo",
        truckNumber: "GJ-01-K1470",
        capacity: 1000,
        img: "https://www.svgrepo.com/show/25233/delivery-truck.svg",
        maxWeight: 100,
        // minWeight: 10
    }, // parcel: [],load:0
    {
        type: "delivery",
        truckNumber: "GJ-01-P1840",
        capacity: 100,
        img: "https://www.iconpacks.net/icons/1/free-truck-icon-1058-thumb.png",
        maxWeight: 10,
        // minWeight: 0
    },
    {
        type: "vehicle",
        truckNumber: "GJ-01-M5470",
        capacity: 10,
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Linecons_small-truck.svg/2048px-Linecons_small-truck.svg.png",
        maxWeight: 1,
        // minWeight: 0
    },
];
